// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type pugiArgsSave struct {
	BufPtr uint64
	Fd     uint64
	Count  uint64
	Flags  uint32
	_      [4]byte
}

type pugiEvent struct {
	Pid         uint32
	Tid         uint32
	Fd          uint32
	Direction   uint32
	DataLen     uint32
	Flags       uint32
	TimestampNs uint64
	Comm        [16]int8
	Data        [8192]uint8
}

// loadPugi returns the embedded CollectionSpec for pugi.
func loadPugi() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PugiBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pugi: %w", err)
	}

	return spec, err
}

// loadPugiObjects loads pugi and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pugiObjects
//	*pugiPrograms
//	*pugiMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPugiObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPugi()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pugiSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pugiSpecs struct {
	pugiProgramSpecs
	pugiMapSpecs
	pugiVariableSpecs
}

// pugiProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pugiProgramSpecs struct {
	TpEnterRead     *ebpf.ProgramSpec `ebpf:"tp_enter_read"`
	TpEnterReadv    *ebpf.ProgramSpec `ebpf:"tp_enter_readv"`
	TpEnterRecvfrom *ebpf.ProgramSpec `ebpf:"tp_enter_recvfrom"`
	TpEnterRecvmsg  *ebpf.ProgramSpec `ebpf:"tp_enter_recvmsg"`
	TpEnterSendmsg  *ebpf.ProgramSpec `ebpf:"tp_enter_sendmsg"`
	TpEnterSendto   *ebpf.ProgramSpec `ebpf:"tp_enter_sendto"`
	TpEnterWrite    *ebpf.ProgramSpec `ebpf:"tp_enter_write"`
	TpEnterWritev   *ebpf.ProgramSpec `ebpf:"tp_enter_writev"`
	TpExitRead      *ebpf.ProgramSpec `ebpf:"tp_exit_read"`
	TpExitReadv     *ebpf.ProgramSpec `ebpf:"tp_exit_readv"`
	TpExitRecvfrom  *ebpf.ProgramSpec `ebpf:"tp_exit_recvfrom"`
	TpExitRecvmsg   *ebpf.ProgramSpec `ebpf:"tp_exit_recvmsg"`
	TpExitSendmsg   *ebpf.ProgramSpec `ebpf:"tp_exit_sendmsg"`
	TpExitSendto    *ebpf.ProgramSpec `ebpf:"tp_exit_sendto"`
	TpExitWrite     *ebpf.ProgramSpec `ebpf:"tp_exit_write"`
	TpExitWritev    *ebpf.ProgramSpec `ebpf:"tp_exit_writev"`
}

// pugiMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pugiMapSpecs struct {
	ActiveArgs *ebpf.MapSpec `ebpf:"active_args"`
	Events     *ebpf.MapSpec `ebpf:"events"`
	TargetPid  *ebpf.MapSpec `ebpf:"target_pid"`
	TempEvent  *ebpf.MapSpec `ebpf:"temp_event"`
}

// pugiVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pugiVariableSpecs struct {
}

// pugiObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPugiObjects or ebpf.CollectionSpec.LoadAndAssign.
type pugiObjects struct {
	pugiPrograms
	pugiMaps
	pugiVariables
}

func (o *pugiObjects) Close() error {
	return _PugiClose(
		&o.pugiPrograms,
		&o.pugiMaps,
	)
}

// pugiMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPugiObjects or ebpf.CollectionSpec.LoadAndAssign.
type pugiMaps struct {
	ActiveArgs *ebpf.Map `ebpf:"active_args"`
	Events     *ebpf.Map `ebpf:"events"`
	TargetPid  *ebpf.Map `ebpf:"target_pid"`
	TempEvent  *ebpf.Map `ebpf:"temp_event"`
}

func (m *pugiMaps) Close() error {
	return _PugiClose(
		m.ActiveArgs,
		m.Events,
		m.TargetPid,
		m.TempEvent,
	)
}

// pugiVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPugiObjects or ebpf.CollectionSpec.LoadAndAssign.
type pugiVariables struct {
}

// pugiPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPugiObjects or ebpf.CollectionSpec.LoadAndAssign.
type pugiPrograms struct {
	TpEnterRead     *ebpf.Program `ebpf:"tp_enter_read"`
	TpEnterReadv    *ebpf.Program `ebpf:"tp_enter_readv"`
	TpEnterRecvfrom *ebpf.Program `ebpf:"tp_enter_recvfrom"`
	TpEnterRecvmsg  *ebpf.Program `ebpf:"tp_enter_recvmsg"`
	TpEnterSendmsg  *ebpf.Program `ebpf:"tp_enter_sendmsg"`
	TpEnterSendto   *ebpf.Program `ebpf:"tp_enter_sendto"`
	TpEnterWrite    *ebpf.Program `ebpf:"tp_enter_write"`
	TpEnterWritev   *ebpf.Program `ebpf:"tp_enter_writev"`
	TpExitRead      *ebpf.Program `ebpf:"tp_exit_read"`
	TpExitReadv     *ebpf.Program `ebpf:"tp_exit_readv"`
	TpExitRecvfrom  *ebpf.Program `ebpf:"tp_exit_recvfrom"`
	TpExitRecvmsg   *ebpf.Program `ebpf:"tp_exit_recvmsg"`
	TpExitSendmsg   *ebpf.Program `ebpf:"tp_exit_sendmsg"`
	TpExitSendto    *ebpf.Program `ebpf:"tp_exit_sendto"`
	TpExitWrite     *ebpf.Program `ebpf:"tp_exit_write"`
	TpExitWritev    *ebpf.Program `ebpf:"tp_exit_writev"`
}

func (p *pugiPrograms) Close() error {
	return _PugiClose(
		p.TpEnterRead,
		p.TpEnterReadv,
		p.TpEnterRecvfrom,
		p.TpEnterRecvmsg,
		p.TpEnterSendmsg,
		p.TpEnterSendto,
		p.TpEnterWrite,
		p.TpEnterWritev,
		p.TpExitRead,
		p.TpExitReadv,
		p.TpExitRecvfrom,
		p.TpExitRecvmsg,
		p.TpExitSendmsg,
		p.TpExitSendto,
		p.TpExitWrite,
		p.TpExitWritev,
	)
}

func _PugiClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pugi_bpfeb.o
var _PugiBytes []byte
